"""user name phone fields

Revision ID: 7c14aa13c4bd
Revises: 10a2e8fe93ff
Create Date: 2026-06-29 18:45:36.606033
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c14aa13c4bd'
down_revision: str | None = '10a2e8fe93ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_tenant_phone', ['tenant_id', 'phone'])
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_users_tenant_phone', type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
